#!/usr/bin/env bash
# pat2pdf version 3.0
# simplified version from https://github.com/newzealandpaul/pat2pdf

# Write to stderr
werr() {
  echo "$*" 1>&2
}

# Die with a message
die() { 
  werr "$*" 
  exit 1
}

# verify the presence of a required executable
verify() {
  [ -x "$(which $1)" ] || die "Error: required executable $1 not found" 
}

verify "wget"
verify "sed"

PATNUM=$( echo $1 | sed 's@,@@g' )

[ -z "$PATNUM" ] && die "usage: pat2pdf <number>|<application number>"
[ -z "${PATNUM##[a-zA-Z1-9][a-zA-Z0-9][0-9][0-9]*}" ] || die "Use a 7 digit patent number."

[ ${#PATNUM} -gt 11 ] && die "Too big a number"

PDF_FILE="pat${PATNUM}.pdf"
wget https://ppubs.uspto.gov/dirsearch-public/print/downloadPdf/$PATNUM -O $PDF_FILE 

open ${PDF_FILE}
